#pragma once

#include "NativeGameplayTags.h"

//Game Abilities Gameplay Tags
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Base);
//Dash
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Dash);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Dash_Active);
//Melee
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_MeleeAttack_Swing);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_MeleeAttack_Swing_Active);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_MeleeAttack_Combo);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_MeleeAttack_Combo_Active);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_MeleeAttack_Base);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_MeleeAttack_Sweep);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_MeleeAttack_Sweep_Active);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_MeleeAttack_Omni);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_MeleeAttack_Omni_Active);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_MeleeAttack_AirCombo);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_MeleeAttack_AirCombo_Active);
//Ranged
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Ranged_Base);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Ranged_Shoot);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Ranged_Shoot_Active);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Ranged_Aim);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Ranged_Aim_Active);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Ranged_Reload);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Ranged_Reload_Active);
//HitReaction
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_HitReaction);
//Die
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Death);
//Active
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Active);

//Gameplay Cues Tags
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayCue_Dash);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayCue_Damage);

//Gameplay Effects Tags
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayEffect_StaminaRegen);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayEffect_HitReaction);

//Gameplay Events Tags
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayEvent_AbilityChanged);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayEvent_Weapon_Equip);
//HitScan
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayEvent_HitScan_Start);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayEvent_HitScan_End);
//MeleeCombo
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayEvent_ContinueCombo_Start);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayEvent_ContinueCombo_End);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayEvent_ContinueCombo_Input);
//Aim
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayEvent_Aim_Start);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayEvent_Aim_End);
//HitType
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayEvent_Hit_Air);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayEvent_Hit_Strong);

//Weapon Tags
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Weapon_Melee);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Weapon_Ranged);

//Data Tags
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Data_Damage);

//State Tags
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_State_Death);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_State_Air);